# Generated by Django 5.0.3 on 2024-03-20 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_band_active_band_biography_band_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='genre',
        ),
    ]
