# Generated by Django 5.0.3 on 2024-03-20 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_band_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='describe',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='sold',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='type',
            field=models.CharField(choices=[('Rd', 'Records'), ('Cl', 'Clothing'), ('Post', 'Posters'), ('M', 'Miscellaneous')], default='M', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='year',
            field=models.IntegerField(default=2001, validators=[django.core.validators.MinValueValidator(2001), django.core.validators.MaxValueValidator(2024)]),
            preserve_default=False,
        ),
    ]
